import = ["~/.config/alacritty/catppuccin-mocha.toml",]
shell = { program = "/opt/homebrew/bin/fish", args = ["-l", "-c", "tmux attach || tmux"] }


[window]
decorations = "Buttonless" # "Full" | "None" | "Transparent" | "Buttonless"
padding = { x = 0, y = 0 }
# opacity = 0
# blur = true

[font]
# normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13.0
